language: node_js
node_js:
- '4.3'
notifications:
  slack:
    secure: GRFG63FrRo0eXkx10lX2KqjgQplxCnFzB+mfQNgATeTsca1lw/K1WWEWJFBa6eP0mdsJHQyhLCUf3lzUHVijeFrqR8A2XQ70CxrO3/InfDhAjKqe8zzTi1j1U9+LWUDY5D7rruRUc9l8TyvnB1f0dcfwTuuWAyxRoW9iCtBdQd4qXU4DHp6i0NypM94qLjYTW69qcR/sYOoeCqaHTuWmfUVHYysNkttjUNAoh8B0sVWzpRUchW4qC0RN1OJFexmKnbISibH51XsSXAqkSpK8ugHSs1qEwAKZsLrhrF9dpvHTa8q+T43V4QxSMtjXcjzO3WV9wZ3Rx4DLe1kotI/AcwO/mKLWytFknCLOi+SgD9yaawj8M+dtGAyuY91d4vJcHuB/s75YT+QmjuGh4Ua06j0uCC0PufwVdZ2k8BlcKiSv0azvIeM/1ZsW7U8kHxzzOlX1AZhqRUqjfDseiTOX2ocOX1cDyUQr4aOvzY9YGvnDDC77gh0g5n7rTPOC1GpdZqipCwt0n2ZAQnbTCXh71j/7G9EdBeH7BvDK7wd2hAsgVNWPWwgT/Jbbq+9UZxhUN0chQD2JYgMBkmMlWUizgdRNR7iqvjTvoWpXxOEI+bzWzFNRZeU/lPaHMCEbHVWUmLeK30UmkHp33FJeaAyRCzHmJlIqBOoo76kWBE/kzpI=
